import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  IgxButtonModule,
  IgxIconModule,
  IgxLayoutModule,
  IgxNavigationDrawerModule,
  IgxRadioModule,
  IgxRippleModule,
  IgxSwitchModule,
  IgxToggleModule,
  IgxNavbarModule,
  IgxSelectModule,
  IgxExpansionPanelModule,
  IgxAutocompleteModule,
  IgxDropDownModule,
  IgxInputGroupModule,
  IgxForOfModule,
  IgxListModule,
  IgxFilterModule,
  IgxDatePickerModule,
  IgxSnackbarModule,
  IgxCardModule,
  IgxMaskModule
} from 'igniteui-angular';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    IgxButtonModule,
    IgxIconModule,
    IgxLayoutModule,
    IgxNavigationDrawerModule,
    IgxRadioModule,
    IgxRippleModule,
    IgxSwitchModule,
    IgxToggleModule,
    IgxNavbarModule,
    IgxSelectModule,
    IgxSwitchModule,
    IgxExpansionPanelModule,
    IgxAutocompleteModule,
    IgxDropDownModule,
    IgxInputGroupModule,
    IgxForOfModule,
    IgxListModule,
    IgxFilterModule,
    IgxDatePickerModule,
    IgxSnackbarModule,
    IgxCardModule,
    IgxMaskModule
  ],
  exports: [
    CommonModule,
    IgxButtonModule,
    IgxIconModule,
    IgxLayoutModule,
    IgxNavigationDrawerModule,
    IgxRadioModule,
    IgxRippleModule,
    IgxSwitchModule,
    IgxToggleModule,
    IgxNavbarModule,
    IgxSelectModule,
    IgxSwitchModule,
    IgxExpansionPanelModule,
    IgxAutocompleteModule,
    IgxDropDownModule,
    IgxInputGroupModule,
    IgxForOfModule,
    IgxListModule,
    IgxFilterModule,
    IgxDatePickerModule,
    IgxSnackbarModule,
    IgxCardModule,
    IgxMaskModule
  ]
})
export class IgniteModule { }
